In [19]:
import os  
import asyncio
from io import BytesIO

import pandas as pd
import gspread
from google.oauth2.service_account import Credentials

from datetime import datetime as dt
from datetime import timedelta

from aiogram import Bot, Dispatcher, F, Router
from aiogram.filters import CommandStart, Command
from aiogram.types import Message, CallbackQuery, InlineKeyboardMarkup, InlineKeyboardButton
from aiogram.utils.keyboard import InlineKeyboardBuilder

import matplotlib.pyplot as plt
import pandas as pd

In [1]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from seaborn) (2.3.4)
Requirement already satisfied: pandas>=1.2 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from seaborn) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\tsyto\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
import numpy as np

In [21]:
dt.today() - timedelta(days=4)

datetime.datetime(2026, 9, 29, 20, 45, 47, 581126)

In [22]:
scopes = [
    'https://www.googleapis.com/auth/spreadsheets',
    'https://www.googleapis.com/auth/drive'
]

creds = Credentials.from_service_account_file('credentials.json', scopes=scopes)
client = gspread.authorize(creds)

yesterday = dt.today() - timedelta(days=1)
months_dict = {
    1: "Январь",
    2: "Февраль",
    3: "Март",
    4: "Апрель",
    5: "Май",
    6: "Июнь",
    7: "Июль",
    8: "Август",
    9: "Сентябрь",
    10: "Октябрь",
    11: "Ноябрь",
    12: "Декабрь"
}
year = yesterday.year
month = months_dict.get(yesterday.month)
day = yesterday.day

full_date  = yesterday.strftime('%d.%m.%Y')
full_date

'02.10.2026'

In [23]:
key = next((k for k, v in months_dict.items() if v == month), None)
prev_month = months_dict.get(key - 1)
prev_month

'Сентябрь'

In [24]:
import re

In [30]:
def get_sample_data():
    sheet = client.open_by_key('8869229955:AAEddtB8es48kh92WU48vVBbu6-6dFrgeKk').worksheet(f'{month} {year}')
    data = sheet.get_all_values()
    df = pd.DataFrame(data)
    df = df.loc[3:]
    df_basic = df.copy()
    df_basic.columns = df.iloc[0]
    df_basic = df_basic[1:].reset_index(drop=True)
    df_basic = df_basic.set_index('Дата')
    
    

    return df_basic

In [31]:
sheet = client.open_by_key('8869229955:AAEddtB8es48kh92WU48vVBbu6-6dFrgeKk').worksheet(f'{month} {year}')
data = sheet.get_all_values()
df_alls = pd.DataFrame(data)

SpreadsheetNotFound: <Response [404]>

In [ ]:
Sales_goal = int(df_alls.iloc[0,34].replace('\xa0', '').replace(' ', ''))
Sales_goal

4700000

In [32]:
df_all = get_sample_data()
df_all = df_all[['Трафик', 'Уникальные', 'vs LY', 'Переход в каталог', 'Положил в корзину', 'Оформил заказ',
                'План Руб', 'План Заказы', 'Заказы Сайт, шт', 'Сумма заказов РУБ']]
df_all = df_all.astype(str).replace(r'\s+', '', regex=True)
df_all = df_all.apply(pd.to_numeric, errors='coerce')
df_all = df_all.iloc[:-2, :]
df_all

SpreadsheetNotFound: <Response [404]>

In [ ]:
df_all[~df_all['Сумма заказов РУБ'].isna()].index[-1]

'24.09.2026'

In [33]:
3986/4700

0.8480851063829787

In [ ]:

sales = df_all['Сумма заказов РУБ'].sum()
print(sales/ Sales_goal)

0.7342772340425532

In [ ]:
sales

np.float64(6902206.0)

In [ ]:
def get_ya_metrik(all_data):
    
    return all_data().iloc[:, :10][['номер недели', 'Трафик', 'Уникальные', 'vs LY', 'Переход в каталог', 'Положил в корзину', 'Оформил заказ']]

In [ ]:
def get_basic_data(all_data):
    return all_data()[['План Руб', 'План Заказы', 'Заказы Сайт, шт', 'Сумма заказов РУБ']]

In [ ]:
def get_reg_info(all_data):
    return all_data().iloc[:, 18:21][[ 'ШТ', 'vs LY']]

In [ ]:
def get_cerf_info(all_data):    
    return all_data()[['Сертификаты, шт', 'Сертификаты, Руб']]

In [ ]:
type(get_sample_data()['Трафик'].loc['13.09.2026'])

str

In [ ]:
df = get_ya_metrik(get_sample_data)
day_ya_info = df.loc[full_date]

day_ya_info = (day_ya_info.astype('str')  
                        .str.replace(r'\s+', '', regex=True)
                        .astype('float32')) # Убираем лишние пробелы во всей таблице и переводим строчные даннын в числовые

In [ ]:
day_ya_info

3
номер недели           39.0
Трафик                662.0
Уникальные            508.0
vs LY                2162.0
Переход в каталог     239.0
Положил в корзину      67.0
Оформил заказ          17.0
Name: 26.09.2026, dtype: float32

In [ ]:
traffic_vs_LY = 100 * day_ya_info['Уникальные']/day_ya_info['vs LY']
CTR_to_catalog = 100 * day_ya_info['Переход в каталог']/day_ya_info['Уникальные']
CTR_to_basket = 100 * day_ya_info['Положил в корзину']/day_ya_info['Уникальные']
CTR_to_order = 100 * day_ya_info['Оформил заказ']/day_ya_info['Уникальные']
print(f' Доля траффика от прошлогоднего: {traffic_vs_LY:,.2f}% \n \
rerere')

 Доля траффика от прошлогоднего: 23.50%
 rerere

In [ ]:
print(f' Доля траффика от прошлогоднего: {traffic_vs_LY:,.2f}% \n \
    CTR перехода в каталог: {CTR_to_catalog:,.2f}% \n \
    CTR добавления в корзину: {CTR_to_basket:,.2f}% \n \
    CTR создания заказа: {CTR_to_order:,.2f}%')

 Доля траффика от прошлогоднего: 23.50%
     CTR перехода в каталог: 47.05%
     CTR добавления в корзину: 13.19%
     CTR создания заказа: 3.35%

In [ ]:
df = get_basic_data(get_sample_data)

day_sales_info = df.loc[full_date]
type(day_sales_info['Сумма заказов РУБ'])

str

In [ ]:
df_sales_last5 = df.loc['14.09.2026':f'{full_date}']
df_sales_last5

3          План Руб План Заказы Заказы Сайт, шт Сумма заказов РУБ
Дата
14.09.2026  156 667                          33           231 402
15.09.2026  156 667                          25           139 929
16.09.2026  210 000                          35           247 279
17.09.2026  150 000                          29           144 670
18.09.2026  150 000                          21           111 400
19.09.2026  150 000                          15            84 917
20.09.2026  150 000                          25           131 729
21.09.2026  150 000                          19            65 120
22.09.2026  150 000                          22           135 290
23.09.2026  150 000                          11            51 700
24.09.2026  150 000                          24           173 355
25.09.2026  154 000
26.09.2026  156 000

In [ ]:
df_sales_last5 = df_sales_last5.astype(str).map(lambda x: re.sub(r'\s+', '', x))
df_sales_last5 = df_sales_last5.apply(pd.to_numeric, errors='coerce').astype('float32')

df_sales_last5

3           План Руб  План Заказы  Заказы Сайт, шт  Сумма заказов РУБ
Дата
14.09.2026  156667.0          NaN             33.0           231402.0
15.09.2026  156667.0          NaN             25.0           139929.0
16.09.2026  210000.0          NaN             35.0           247279.0
17.09.2026  150000.0          NaN             29.0           144670.0
18.09.2026  150000.0          NaN             21.0           111400.0
19.09.2026  150000.0          NaN             15.0            84917.0
20.09.2026  150000.0          NaN             25.0           131729.0
21.09.2026  150000.0          NaN             19.0            65120.0
22.09.2026  150000.0          NaN             22.0           135290.0
23.09.2026  150000.0          NaN             11.0            51700.0
24.09.2026  150000.0          NaN             24.0           173355.0
25.09.2026  154000.0          NaN              NaN                NaN
26.09.2026  156000.0          NaN              NaN                NaN

In [ ]:
df_sales_last5['Доля'] = df_sales_last5['Сумма заказов РУБ']/ df_sales_last5['План Руб'] 
df_sales_last5['Ср. чек'] = df_sales_last5['Сумма заказов РУБ']/ df_sales_last5['Заказы Сайт, шт']
df_sales_last5 = df_sales_last5.fillna('нет данных')
df_sales_last5

3,План Руб,План Заказы,"Заказы Сайт, шт",Сумма заказов РУБ,Доля,Ср. чек
Дата,,,,,,
14.09.2026,156667.0,нет данных,33.0,231402.0,1.477031,7012.181641
15.09.2026,156667.0,нет данных,25.0,139929.0,0.893162,5597.160156
16.09.2026,210000.0,нет данных,35.0,247279.0,1.177519,7065.114258
17.09.2026,150000.0,нет данных,29.0,144670.0,0.964467,4988.620605
18.09.2026,150000.0,нет данных,21.0,111400.0,0.742667,5304.761719
19.09.2026,150000.0,нет данных,15.0,84917.0,0.566113,5661.133301
20.09.2026,150000.0,нет данных,25.0,131729.0,0.878193,5269.160156
21.09.2026,150000.0,нет данных,19.0,65120.0,0.434133,3427.368408
22.09.2026,150000.0,нет данных,22.0,135290.0,0.901933,6149.54541
23.09.2026,150000.0,нет данных,11.0,51700.0,0.344667,4700.0
24.09.2026,150000.0,нет данных,24.0,173355.0,1.1557,7223.125
25.09.2026,154000.0,нет данных,нет данных,нет данных,нет данных,нет данных
26.09.2026,156000.0,нет данных,нет данных,нет данных,нет данных,нет данных

In [ ]:
df_sales_last5.index

Index(['14.09.2026', '15.09.2026', '16.09.2026', '17.09.2026', '18.09.2026',
       '19.09.2026', '20.09.2026', '21.09.2026', '22.09.2026', '23.09.2026',
       '24.09.2026', '25.09.2026', '26.09.2026'],
      dtype='object', name='Дата')

In [ ]:
df_ = get_ya_metrik(get_sample_data).loc[df_sales_last5.index]

In [ ]:
df_.index[-1].split('.')[0]

'26'

In [ ]:
int(full_date.split('.')[0])

26

In [ ]:
df_res = pd.concat([df_, df_sales_last5], axis=1)
df_res

3,номер недели,Трафик,Уникальные,vs LY,Переход в каталог,Положил в корзину,Оформил заказ,План Руб,План Заказы,"Заказы Сайт, шт",Сумма заказов РУБ,Доля,Ср. чек
Дата,,,,,,,,,,,,,
14.09.2026,38,991,775,1 900,316,94,30,156667.0,нет данных,33.0,231402.0,1.477031,7012.181641
15.09.2026,38,883,688,2 638,269,73,18,156667.0,нет данных,25.0,139929.0,0.893162,5597.160156
16.09.2026,38,993,788,2 569,303,91,28,210000.0,нет данных,35.0,247279.0,1.177519,7065.114258
17.09.2026,38,848,646,2 635,270,82,22,150000.0,нет данных,29.0,144670.0,0.964467,4988.620605
18.09.2026,38,765,590,2 278,238,67,17,150000.0,нет данных,21.0,111400.0,0.742667,5304.761719
19.09.2026,38,737,578,2 151,212,68,12,150000.0,нет данных,15.0,84917.0,0.566113,5661.133301
20.09.2026,39,787,584,2 129,228,67,29,150000.0,нет данных,25.0,131729.0,0.878193,5269.160156
21.09.2026,39,909,708,2 206,248,71,13,150000.0,нет данных,19.0,65120.0,0.434133,3427.368408
22.09.2026,39,786,639,2 501,249,69,16,150000.0,нет данных,22.0,135290.0,0.901933,6149.54541
23.09.2026,39,798,646,2 570,224,68,12,150000.0,нет данных,11.0,51700.0,0.344667,4700.0
24.09.2026,39,945,743,2 451,298,72,18,150000.0,нет данных,24.0,173355.0,1.1557,7223.125
25.09.2026,39,814,666,2 619,263,96,20,154000.0,нет данных,нет данных,нет данных,нет данных,нет данных
26.09.2026,39,662,508,2 162,239,67,17,156000.0,нет данных,нет данных,нет данных,нет данных,нет данных